### ISSUE TITLE
Update to Electron 7

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation-app#102]
# Describe the problem
Native support for dark mode! Unblocks #99 

## Related issues
#99 
https://github.com/electron/electron/pull/19758
https://github.com/electron/electron/pull/18981
https://github.com/electron/electron/pull/19226

**Comment by tyler-ball** [comment]
Bot PR to bump this: https://github.com/chef/chef-workstation-app/pull/101

**Comment by afiune** [comment]
Closed by https://github.com/chef/chef-workstation-app/pull/101
