### ISSUE TITLE
Support darkmode throughout the UI

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation-app#103]
# Describe the problem
Our app does not respect darkmode on systems which makes it look out of place. With macOS Catalina out a lot of users are going to have darkmode enabled. We need to properly handle this so our app looks native on those systems.

## Software Version
Chef Workstation 0.10

## Replication Case
Switch the system to darkmode. Check the menubar icon and the UI windows.

<img width="62" alt="Screen Shot 2019-10-23 at 10 46 46 AM" src="https://user-images.githubusercontent.com/1015200/67419909-704a9380-f582-11e9-8937-8df95d848140.png">

<img width="622" alt="Screen Shot 2019-10-23 at 10 46 35 AM" src="https://user-images.githubusercontent.com/1015200/67419918-73de1a80-f582-11e9-8544-81341d5430e9.png">

<img width="532" alt="Screen Shot 2019-10-23 at 10 46 27 AM" src="https://user-images.githubusercontent.com/1015200/67419941-7e001900-f582-11e9-876a-d09df1ac11cd.png">

**Comment by tas50** [comment]
Requires #101. Includes the issue in #99

**Comment by tas50** [comment]
Magically fixed with electron 7

![image](https://user-images.githubusercontent.com/1015200/67544154-32945a80-f6a9-11e9-89fe-715c1066752b.png)

**Comment by tas50** [comment]
https://medium.com/missive-app/make-your-electron-app-dark-mode-compatible-c23dcfdd0dfa

**Comment by afiune** [comment]
https://github.com/chef/chef-workstation-app/pull/101 has been merged but I think
to have full dark mode support we still need to modify things inside the app, I will
leave this issue open.

**Comment by afiune** [comment]
Closed by https://github.com/chef/chef-workstation-app/pull/101
