### ISSUE TITLE
About Workstation window has a scrollbar on macOS Catalina now

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation-app#104]
# Describe the problem
I know we had this issue in the past and it looks like it's back. We have a scrollbar in the window again.

## Software Version
Workstation 0.10.32

## Replication Case
Select about chef workstation from the menu bar.

<img width="622" alt="Screen Shot 2019-10-23 at 10 53 04 AM" src="https://user-images.githubusercontent.com/1015200/67420355-52c9f980-f583-11e9-81a8-35b26abc5327.png">

**Comment by tas50** [comment]
This appears to be fixed with Electron 7 
<img width="622" alt="image" src="https://user-images.githubusercontent.com/1015200/67544206-64a5bc80-f6a9-11e9-8a28-ed11b73328aa.png">

**Comment by afiune** [comment]
For what is worth, the scroll bar was introduced back when we added the
`Apache License Version 2.0` line. Though, we should just disable it with the
caveat that if we put more stuff the user might not be able to see what's in the
window since you can't resize it either.

**Comment by tas50** [comment]
It's not there by default now so I consider this fixed. If you scroll your mouse within the window you see it, but that's fine for now.
