### ISSUE TITLE
Feature flag setting in Workstation Tray app - UX designs 

### ISSUE THREAD

**Issue by jyan-chef** [chef/chef-workstation-app#129]
UX mockups needed for new settings within the Workstation tray app to turn feature flags on/off. 

Summary
Feature flags are used to hide and unhide experimental/pre-release features in Workstation. Note - feature flags can also be set via a config file in the CLI

Assumptions/Limitations
- Legal disclosure needs to be shown to user when turning feature flags on to indicate the function is not under warranty 
- Legal approval required for final design in terms of how the disclosure is displayed

Requirements
- User should see all available features that can be turned on or off
- User should have some controller to turn feature flags on and off 
- User should be shown some info on what the feature flag is for and where it takes effect 

Additional thoughts
- Would be nice if the feature flags themselves can be grouped separately from the legal disclosure (e.g. in some kind of container or some type of separation. The goal would be to visually separate the legal stuff from the feature flags and make it easier to understand what's shown to the user)

**Comment by tyler-ball** [comment]
@susanev We're working on sprint planning - do you know where this card falls in your priority list? I added it to the current sprint for now but we can move it depending on your priorities.

**Comment by susanev** [comment]
@tyler-ball I think we are just waiting on legal

**Comment by afiune** [comment]
@susanev would you be able to create the designs of the feature flags tab in the preference dialog for Windows systems?

**Comment by tyler-ball** [comment]
Closed by #125
