### ISSUE TITLE
Preferences Dialog: Implement the Notifications Tab

### ISSUE THREAD

**Issue by afiune** [chef/chef-workstation-app#159]
# Description
Placeholder to implement the Notifications tab inside the Preferences Dialog.

<img width="612" alt="Screen Shot 2020-02-10 at 2 10 49 AM" src="https://user-images.githubusercontent.com/5712253/74194764-29f37000-4c17-11ea-8d3d-90706b480b79.png">

This tab is currently commented out.

**Comment by tyler-ball** [comment]
Related: #158

**Comment by tas50** [comment]
Closing this out right now since we don't have enough content to justify a whole preference panel
