### ISSUE TITLE
Release notes link does not work when subscribed to 'current' channel

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation-app#163]
# Describe the problem
Clicking on the link will always take users to a 404 page because we do not generate release notes until we perform the stable channel release.

## Software Version
Chef Workstation 0.15.18

## Replication Case
Subscribe to current channel
Download and install latest current channel Chef Workstation
Restart the CW app, open the about page and click the 'Release Notes' link

## Possible Solution
Users suggested a couple of possible solutions:
* Grey out 'release notes' if the user is subscribed to the current channel
* Change the link to take users to the current Changelog if they are subscribed to the current channel (and change the link name from 'Release Notes' to 'Current Changelog')

**Comment by tas50** [comment]
This is partially fixed now that we just link to the docs site. It'll show the last released instead of failing
