### ISSUE TITLE
Unhandled exception when there is no internet

### ISSUE THREAD

**Issue by probonopd** [chef/chef-workstation-app#20]
Unhandled exception when there is no internet:

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/3713aac86baf3db9e39e4d7edf9fd2ca71746e7d/database/chef-workstation/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/pull/785

**Comment by tyler-ball** [comment]
This does not surprise me at all. We're still in the _super_ early stages for this @probonopd - but thank you for the issue!
