### ISSUE TITLE
Workstation tray icon not appearing on Linux

### ISSUE THREAD

**Issue by marcparadise** [chef/chef-workstation-app#221]
When launching the latest stable Workstation tray app on linux, the icon does not show up in the tray.  Pop-up dialogs (notifications, errors) still render. 

I've tried this on arch linux and ubuntu 18.04.

**Comment by tyler-ball** [comment]
Maybe unrelated, but when trying to do a local build of the tray app on Darwin I couldn't get it to run in `debug` mode. It would pop open a bouncing dock icon but would never start the tray app. Non-debug mode worked fine though ¯\_(ツ)_/¯

**Comment by nikhil2611** [comment]
Related PR: https://github.com/chef/chef-workstation/pull/2402

**Comment by nikhil2611** [comment]
https://github.com/chef/chef-workstation/pull/2434
