### ISSUE TITLE
Workstation crashes hard if the installation in /opt is removed

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation-app#293]
If you delete the installation from /opt, and the menu bar app then launches it crashes in a very unpleasant way. First you get a random stacktrace error message, and then you every click to the menu bar does nothing. The only way to actually quit it is to find it in the activity monitor and kill the process.

<img width="488" alt="screen shot 2018-10-29 at 4 55 54 pm" src="https://user-images.githubusercontent.com/1015200/47687072-bbaea980-db9b-11e8-8f92-ae6adc214e83.png">

**Comment by tas50** [comment]
We probably need to hard fail and quit the app if the /opt/chef-workstation dir is not present. We can check that during the startup of the toolbar app.

**Comment by marcparadise** [comment]
Let's do that, with a message like, "Please install Chef Workstation prior to running this App".

**Comment by nikhil2611** [comment]
This issue is no longer valid to the latest version of workstation.
