### ISSUE TITLE
Already up to date windows show scroll bars

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation-app#312]
We need to fix the sizing of this content and window to avoid the scrollbar

![Screen Shot 2021-02-15 at 7 51 49 PM](https://user-images.githubusercontent.com/1015200/108574242-b8d7a580-72cb-11eb-98a0-2d25ab2de391.png)

![Screen Shot 2021-02-15 at 3 56 44 PM](https://user-images.githubusercontent.com/1015200/108574253-c1c87700-72cb-11eb-89e5-33f0d9852a96.png)

**Comment by SmishaM** [comment]
Hi @tas50,

I tried replicating the issue on my **MacBook Pro (16-inch, 2019)**, but there is no scroll bar in the check for updates window. Can you please confirm for which specific condition or **screen resolution** this issue occurs.

The screenshot for the same is attached.
![Screenshot 2021-03-03 at 10.41.57 AM.png](https://images.zenhubusercontent.com/5faa1bf838c6403ac7f77fe1/79ba8ef9-56ce-44fa-b236-17e53530fb98)

**Comment by tas50** [comment]
It looks like it depends on your scrollbar settings. If you have the auto scrollbar settings for mouse usage they're showing up while they don't show up in other apps. I think we just have too much extra whitespace for the window size which makes the content larger than the window.

![image](https://user-images.githubusercontent.com/1015200/109834216-cf98c900-7bf6-11eb-90cf-a6049bc2fefa.png)

**Comment by SmishaM** [comment]
@tas50, my scroll settings is same as yours ie., (auto scrollbar settings), but the issue is not reproducible.
![Screenshot 2021-03-03 at 9.55.05 PM.png](https://images.zenhubusercontent.com/5faa1bf838c6403ac7f77fe1/5664260f-ae73-4cf2-a80d-a2014ce6a376)

Do you suggest resizing of the window to remove extra spaces? If so, Do we have UX/UI design for the same?

**Comment by tas50** [comment]
Closing this out based on the feedback
