### ISSUE TITLE
Preference window does not display correctly on macOS

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation-app#313]
![Screen Shot 2021-02-15 at 3 57 54 PM](https://user-images.githubusercontent.com/1015200/108574300-defd4580-72cb-11eb-9b66-b946a44e4417.png)

When you hover over the close/minimize widgets they render oddly

**Comment by SmishaM** [comment]
Hi @tas50,

I tried replicating the issue on my **MacBook Pro (16-inch, 2019)**, but there is no distortion in the icons. Can you please confirm for which specific condition or **screen resolution** this issue occurs.

The screenshot for the same is attached.
[Uploading... Screenshot 2021-03-03 at 10.40.15 AM.png]

**Comment by SmishaM** [comment]
Also, checked in MAC system whose screen size of 13.5". The UI is proper.

**Comment by tas50** [comment]
This is fixed on the later releases
