### ISSUE TITLE
Update dialog box doesn't rendor correctly on macOS

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation-app#60]
This is the text box I was given to upgrade today:

![image](https://user-images.githubusercontent.com/1015200/47450502-3c277180-d77a-11e8-96d3-f9d75234b1be.png)

**Comment by afiune** [comment]
This is not currently an issue since we no longer show the latest version, instead we just tell users that there is an update available. (Look at https://github.com/chef/chef-workstation-app/pull/75 for reference)
