### ISSUE TITLE
? icon in the About Chef Workstation does nothing

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation-app#62]
When in the About Chef Workstation dialog if you click the ? icon it does nothing.

**Comment by afiune** [comment]
This is the `?` in question:

<img width="506" alt="Screen Shot 2019-09-10 at 5 03 50 PM" src="https://user-images.githubusercontent.com/5712253/64656542-079dc200-d3ed-11e9-9833-fb04860301ab.png">
