### ISSUE TITLE
New version is missing in the Update Available dialog

### ISSUE THREAD

**Issue by stuartpreston** [chef/chef-workstation-app#67]
Platform:
macOS 10.14.1

Version:
Chef Workstation 0.2.29

After switching to the "current" channel,and verifying that the downloads site showed new versions of the software to install I tried the "Check for update" functionality in the Chef Workstation App.

I received a message:
```
"is the latest current release, you have 0.2.29"
```

I expected to see:
```
"0.2.32 is the latest current release, you have 0.2.29"
```

The download does proceed as normal, so hopefully this is a simple fix to the dialog.

![image](https://user-images.githubusercontent.com/6384654/48272381-5cbc2080-e436-11e8-8e98-b84944f893c5.png)

**Comment by afiune** [comment]
@stuartpreston I have verified the functionality that is currently implemented and will be released in the new version of Chef Workstation and that resolves this issue in the following manner, when WS needs an update, it won't tell you the version but instead, that there is an available update and a button to proceed. 

This image shows a different icon when there is an update available and the dropdown menu to download it. 
 
<img width="208" alt="Screen Shot 2019-09-10 at 8 30 37 AM" src="https://user-images.githubusercontent.com/5712253/64624798-69880880-d3a8-11e9-85f3-01de52f57d88.png">

After download and install you will see that the icon goes back to normal (without the red dot) that indicates that you are running on the latest version.

<img width="618" alt="Screen Shot 2019-09-10 at 8 43 58 AM" src="https://user-images.githubusercontent.com/5712253/64624578-2037b900-d3a8-11e9-85a9-86bf71e0af11.png">

You can also verify for updates as before:

<img width="209" alt="Screen Shot 2019-09-10 at 8 51 25 AM" src="https://user-images.githubusercontent.com/5712253/64624695-46f5ef80-d3a8-11e9-843e-1c95be75b015.png">

<img width="419" alt="Screen Shot 2019-09-10 at 8 44 19 AM" src="https://user-images.githubusercontent.com/5712253/64624630-30e82f00-d3a8-11e9-9b8b-10320b9fe8b4.png">

If this doesn't satisfice the issue please feel free to re-open. Thank you for your feedback.
