### ISSUE TITLE
Chef Workstation App should have a splash screen

### ISSUE THREAD

**Issue by docwhat** [chef/chef-workstation-app#71]
## Description

The "Chef Workstation App" (on macOS at least) should have a splash screen or animation to show that it is in the menu bar.

Note: It shouldn't do this animation if started automatically on booting.

Reasoning:

I just spent a bunch of time uninstalling and re-installing Chef Workstation because I thought the Chef Workstation App was broken.  I didn't realize that it only a (simple) menu app.

## Chef Workstation Version

0.2.41

## Platform Version

macOS 10.14.1

**Comment by tas50** [comment]
Here's a thread with some talk about how to know how we're launched:

https://github.com/Teamwork/node-auto-launch/issues/93

**Comment by tas50** [comment]
This should probably be a larger version of the same icon we use on the about page currently
