### ISSUE TITLE
The menu bar icon needs a dark mode version

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation-app#99]
# Describe the problem
You can't see the menu bar icon in dark mode and it doesn't match the icons of other apps in the menu bar

## Software Version
0.10

## Replication Case
Launch the menu bar when your mac is in dark mode

## Possible Solution
Get a white version of the icon and see if Electron surfaces dark mode

**Comment by afiune** [comment]
Now you can! https://github.com/chef/chef-workstation-app/pull/101

![tenor-227004822](https://user-images.githubusercontent.com/5712253/67582702-761db180-f707-11e9-8655-2ebc4e691d49.gif)
